version: "2.3"

services:

  nucleus:
    container_name: nucleus
    build:
      context: .
      dockerfile: Dockerfile
      target: nucleus
      args:
        BASE_IMAGE: elementaryrobotics/atom:v2.5.2-base-stock-amd64
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - log:/var/log/atom
      # Link in the database
      #- "./metrics/data:/metrics"
      # Need to see /proc for psutil
      - "/proc:/host/proc:ro"
      # Link in the monitoring folder s.t. we can develop
      - "./metrics/monitoring:/usr/local/bin/monitoring"
      # Launch script for debug
      - "./config/nucleus/launch.sh:/atom/launch.sh"
      # Wait for nucleus script, for debug
      - "./utilities/wait_for_nucleus.sh:/usr/local/bin/wait_for_nucleus.sh"
    network_mode: host
    environment:
      - "METRICS_MONITOR_PROCFS=/host/proc"
      - "ATOM_USE_METRICS=TRUE"
    privileged: true

  metrics:
    container_name: metrics
    build:
      context: .
      dockerfile: metrics/Dockerfile
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      # Link in the dashboards s.t. we can develop
      - "./metrics/dashboards:/metrics/dashboards"
      # Wait for nucleus script, for debug
      - "./utilities/wait_for_nucleus.sh:/usr/local/bin/wait_for_nucleus.sh"
    network_mode: "service:nucleus"
    environment:
      - "ATOM_USE_METRICS=TRUE"

  atom:
    container_name: atom
    build:
      context: .
      dockerfile: Dockerfile
      target: test
      args:
        BASE_IMAGE: elementaryrobotics/atom:v2.5.2-base-opencv-amd64
    volumes:
      - type: volume
        source: shared
        target: /shared
        volume:
          nocopy: true
      - ".:/atom"
      - log:/var/log/atom
    network_mode: host
    depends_on:
      - "nucleus"
    environment:
      - "ATOM_USE_METRICS=TRUE"
    command: tail -f /dev/null

  formatting:
    container_name: formatting
    build:
      context: ./utilities/formatting
      dockerfile: Dockerfile
    volumes:
      - ".:/code"
      - "./utilities/formatting/run.sh:/usr/local/bin/run.sh"
    environment:
      - "DO_FORMAT="

volumes:
  shared:
    driver_opts:
      type: tmpfs
      device: tmpfs
  log:
    driver_opts:
      type: tmpfs
      device: tmpfs
